// <auto-generated />
using System;
using CBAS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CBAS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506100000_AddShipperSamples")]
    partial class AddShipperSamples
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CBAS.Web.Models.ShipperSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ExtractedExcelJson").HasColumnType("text");
                    b.Property<string>("ExtractedPdfText").HasColumnType("text");
                    b.Property<byte[]>("SampleExcelResult").IsRequired().HasColumnType("bytea");
                    b.Property<string>("SampleExcelFileName").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<byte[]>("SampleOfferPdf").IsRequired().HasColumnType("bytea");
                    b.Property<string>("SampleOfferFileName").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<int>("ShipperId").HasColumnType("integer");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ShipperId").IsUnique();
                    b.ToTable("ShipperSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
