// <auto-generated />
using System;
using CBAS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CBAS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507100000_AddAppSettings")]
    partial class AddAppSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CBAS.Web.Models.AppSetting", b =>
                {
                    b.Property<string>("Key").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Value").HasColumnType("text");
                    b.HasKey("Key");
                    b.ToTable("AppSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
