// <auto-generated />
using System;
using CBAS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CBAS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CBAS.Web.Models.HVIReport", b =>
                {
                    b.Property<int>("HVIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HVIId"));
                    b.Property<string>("ColorGrade").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<decimal?>("ColorRd").HasColumnType("decimal(5,2)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CropYear").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("FileName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<decimal?>("Leaf").HasColumnType("decimal(5,2)");
                    b.Property<decimal?>("Length").HasColumnType("decimal(5,2)");
                    b.Property<string>("LotCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int?>("MasterLotId").HasColumnType("integer");
                    b.Property<decimal?>("Micronaire").HasColumnType("decimal(5,2)");
                    b.Property<string>("RawDataJson").HasColumnType("text");
                    b.Property<decimal?>("StrengthGPT").HasColumnType("decimal(5,2)");
                    b.Property<int?>("TotalBales").HasColumnType("integer");
                    b.Property<decimal?>("Uniformity").HasColumnType("decimal(5,2)");
                    b.HasKey("HVIId");
                    b.HasIndex("LotCode").IsUnique();
                    b.HasIndex("MasterLotId");
                    b.ToTable("HVIReports");
                });

            modelBuilder.Entity("CBAS.Web.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CropYear").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<int?>("HVIReportId").HasColumnType("integer");
                    b.Property<int?>("LatestOfferId").HasColumnType("integer");
                    b.Property<string>("LotCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Origin").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<decimal>("QuantityAvailable").HasColumnType("numeric(10,2)");
                    b.Property<decimal>("QuantityOriginal").HasColumnType("numeric(10,2)");
                    b.Property<int>("ShipperId").HasColumnType("integer");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<string>("Type").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("HVIReportId");
                    b.HasIndex("LatestOfferId");
                    b.HasIndex("LotCode").IsUnique();
                    b.HasIndex("ShipperId");
                    b.ToTable("Lots");
                });

            modelBuilder.Entity("CBAS.Web.Models.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfferId"));
                    b.Property<decimal>("CommissionPercent").HasColumnType("decimal(5,2)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("FileName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<decimal>("ICEValue").HasColumnType("decimal(10,2)");
                    b.Property<string>("ICESettlementsJson").HasColumnType("text");
                    b.Property<DateTime>("OfferDate").HasColumnType("timestamp with time zone");
                    b.Property<int?>("ShipperId").HasColumnType("integer");
                    b.Property<string>("SupplierName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.HasKey("OfferId");
                    b.HasIndex("ShipperId");
                    b.ToTable("Offers");
                });

            modelBuilder.Entity("CBAS.Web.Models.OfferLot", b =>
                {
                    b.Property<int>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LotId"));
                    b.Property<decimal>("BasisCents").HasColumnType("decimal(10,2)");
                    b.Property<string>("ColorSpec").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("CropYear").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("LeafSpec").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("LengthSpec").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("LotCode").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("MicronaireSpec").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<int>("OfferId").HasColumnType("integer");
                    b.Property<string>("Origin").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<decimal>("OutrightPrice").HasColumnType("decimal(10,2)");
                    b.Property<decimal>("PriceCentsPerLb").HasColumnType("decimal(10,4)");
                    b.Property<decimal>("Quantity").HasColumnType("decimal(10,2)");
                    b.Property<string>("QuantityText").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("SettlementMonth").HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<DateTime?>("ShipmentDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("ShipmentDateText").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("SpecialSpec").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("StrengthSpec").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int?>("MasterLotId").HasColumnType("integer");
                    b.HasKey("LotId");
                    b.HasIndex("LotCode");
                    b.HasIndex("MasterLotId");
                    b.HasIndex("OfferId");
                    b.ToTable("OfferLots");
                });

            modelBuilder.Entity("CBAS.Web.Models.Shipper", b =>
                {
                    b.Property<int>("ShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipperId"));
                    b.Property<string>("ContactInfo").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("Phone").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.HasKey("ShipperId");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("CBAS.Web.Models.ProcessedOutput", b =>
                {
                    b.Property<int>("OutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OutputId"));
                    b.Property<decimal>("Basis").HasColumnType("decimal(10,2)");
                    b.Property<string>("Color").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CropYear").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<decimal?>("Leaf").HasColumnType("decimal(5,2)");
                    b.Property<decimal?>("Length").HasColumnType("decimal(5,2)");
                    b.Property<int>("LotId").HasColumnType("integer");
                    b.Property<decimal?>("Micronaire").HasColumnType("decimal(5,2)");
                    b.Property<string>("MicronaireText").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<decimal>("NetPrice").HasColumnType("decimal(10,4)");
                    b.Property<string>("Notes").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<int>("OfferId").HasColumnType("integer");
                    b.Property<string>("Origin").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<decimal>("PriceCentsPerKg").HasColumnType("decimal(10,4)");
                    b.Property<decimal>("PriceWithCommission").HasColumnType("decimal(10,4)");
                    b.Property<decimal>("Quantity").HasColumnType("decimal(10,2)");
                    b.Property<string>("QuantityText").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("STT").HasColumnType("integer");
                    b.Property<DateTime?>("ShipmentDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("ShipmentDateText").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("SpecialSpec").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<decimal?>("StrengthMin").HasColumnType("decimal(5,2)");
                    b.Property<string>("StrengthText").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.HasKey("OutputId");
                    b.HasIndex("LotId");
                    b.HasIndex("OfferId");
                    b.ToTable("ProcessedOutputs");
                });

            modelBuilder.Entity("CBAS.Web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("FullName").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<DateTime?>("LastLoginAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.HasKey("UserId");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("CBAS.Web.Models.HVIReport", b =>
                {
                    b.HasOne("CBAS.Web.Models.Lot", "MasterLot")
                        .WithMany()
                        .HasForeignKey("MasterLotId");
                    b.Navigation("MasterLot");
                });

            modelBuilder.Entity("CBAS.Web.Models.Lot", b =>
                {
                    b.HasOne("CBAS.Web.Models.HVIReport", "HVIReport")
                        .WithMany()
                        .HasForeignKey("HVIReportId");
                    b.HasOne("CBAS.Web.Models.Offer", "LatestOffer")
                        .WithMany()
                        .HasForeignKey("LatestOfferId");
                    b.HasOne("CBAS.Web.Models.Shipper", "Shipper")
                        .WithMany("Lots")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("HVIReport");
                    b.Navigation("LatestOffer");
                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("CBAS.Web.Models.Offer", b =>
                {
                    b.HasOne("CBAS.Web.Models.Shipper", "Shipper")
                        .WithMany("Offers")
                        .HasForeignKey("ShipperId");
                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("CBAS.Web.Models.OfferLot", b =>
                {
                    b.HasOne("CBAS.Web.Models.Lot", "MasterLot")
                        .WithMany()
                        .HasForeignKey("MasterLotId");
                    b.HasOne("CBAS.Web.Models.Offer", "Offer")
                        .WithMany("OfferLots")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("MasterLot");
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("CBAS.Web.Models.ProcessedOutput", b =>
                {
                    b.HasOne("CBAS.Web.Models.OfferLot", "OfferLot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("CBAS.Web.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Offer");
                    b.Navigation("OfferLot");
                });

            modelBuilder.Entity("CBAS.Web.Models.Offer", b =>
                {
                    b.Navigation("OfferLots");
                });

            modelBuilder.Entity("CBAS.Web.Models.Shipper", b =>
                {
                    b.Navigation("Lots");
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
