// <auto-generated />
using System;
using CBAS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CBAS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CBAS.Web.Models.HVIReport", b =>
                {
                    b.Property<int>("HVIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HVIId"));

                    b.Property<string>("ColorGrade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ColorRd")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropYear")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Leaf")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Micronaire")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("StrengthGPT")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TotalBales")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Uniformity")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("HVIId");

                    b.HasIndex("LotCode")
                        .IsUnique();

                    b.ToTable("HVIReports");
                });

            modelBuilder.Entity("CBAS.Web.Models.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfferId"));

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ICEValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("OfferId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("CBAS.Web.Models.OfferLot", b =>
                {
                    b.Property<int>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LotId"));

                    b.Property<decimal>("BasisPoints")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CropYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceCentsPerLb")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialSpec")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LotId");

                    b.HasIndex("LotCode");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferLots");
                });

            modelBuilder.Entity("CBAS.Web.Models.ProcessedOutput", b =>
                {
                    b.Property<int>("OutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OutputId"));

                    b.Property<decimal>("Basis")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Leaf")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LotId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Micronaire")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceCentsPerKg")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("PriceWithCommission")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("STT")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialSpec")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("StrengthMin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OutputId");

                    b.HasIndex("LotId");

                    b.HasIndex("OfferId");

                    b.ToTable("ProcessedOutputs");
                });

            modelBuilder.Entity("CBAS.Web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CBAS.Web.Models.OfferLot", b =>
                {
                    b.HasOne("CBAS.Web.Models.HVIReport", "HVIReport")
                        .WithMany("OfferLots")
                        .HasForeignKey("LotCode")
                        .HasPrincipalKey("LotCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("CBAS.Web.Models.Offer", "Offer")
                        .WithMany("OfferLots")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HVIReport");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("CBAS.Web.Models.ProcessedOutput", b =>
                {
                    b.HasOne("CBAS.Web.Models.OfferLot", "OfferLot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CBAS.Web.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("OfferLot");
                });

            modelBuilder.Entity("CBAS.Web.Models.HVIReport", b =>
                {
                    b.Navigation("OfferLots");
                });

            modelBuilder.Entity("CBAS.Web.Models.Offer", b =>
                {
                    b.Navigation("OfferLots");
                });
#pragma warning restore 612, 618
        }
    }
}
